[features]
seeds = false
skip-lint = false

[programs.devnet]
gentlyos_genesis = "GENTLYosxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
